### ISSUE TITLE
EU Region Support missing

### ISSUE THREAD

**Issue by Slind14** [sematext/docker-spm-client#3]
Hi Sematext Team,

at the moment this docker image can not be used for the EU region. Any chance you can add support and push to docker hub?
Thanks

**Comment by megastef** [comment]
Hi, 

you can use REGION=EU with `sematext/spm-client:auto-discovery` image. 
https://github.com/sematext/docker-spm-client/blob/auto-discovery/run.sh#L119-L129

Please note we will release in the next few weeks a new version of auto-discovery with a different image. You will find instructions in Sematext UI. 

Stefan
